= Celestial
Ronen Narkis, <narkisr@gmail.com> v0.13.4
:toc: left
:!numbered:
:idseparator: -
:idprefix:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:
:ubuntuversion: 16.x
:redisversion: 3.x
:celestialversion: 0.13.4
:javaversion: 1.8.x
:imagesdir: docs/img

== Introduction 

Celestial is a server that enables to manage machines life cycle from initial VM creation to deployment automation and user access control,

== Setup

Celestial was designed with deployment simplicity in mind, only two services are required to run Celestial itself and a link:http://redis.io/[Redis] instance,

Perquisites:

*   Ubuntu {ubuntuversion}
*   Java {javaversion}
*   Redis >= {redisversion}

The following options are available to get started quickly:

* Use Vagrant to set up a VM running Celestial
* User Docker compose to launch Celestial container with its dependencies.

There are a couple of options to get Celestial going, using a dedicate Ubuntu VM and the install script is the recommended production option.

=== Vagrant

If you don't have an Ubuntu machine then using Vagrant is an excellent option to test Celestial quickly (make sure to have link:http://opskeleton.github.io/opskeleton/latest/#installation[opskeleton] perquisites installed):

```bash
$ git clone git://github.com/opskeleton/celestial-sandbox.git
$ ./boot.sh
```

Once its done running you have a celestial instance ready and running now:

* Point your browser to https://{hostname}:8443/ (admin/changeme)
* Head on to <<Walkthrough>> section.

== Walkthrough

TBD 

=== Where to go next

Celestial integrated with many other tools and components, you can set it up to:

*   Start to manage other hypervisors including <<AWS>>, <<Proxmox>>, <<GCE>>, <<Openstack>>, <<KVM>>, <<Digitalocean>>.
*   Register hosts atomically in DNS using link:http://www.thekelleys.org.uk/dnsmasq/doc.html[dnsmasq] <<hooks>>.
*   Publish Celestial logs into a central logging system (Kibana) for auditing the history of your infrastructure changes and track logical workflow <<Transactions>>.
*   Give access to other users and group within your organization to automatically provisioned machines, you can set quotas and limit which environment each user can access.
*   Use the Restful API and automate nightly build machines, use link:#development[Swagger] to move quickly and learn what can be done.

## Configuration

### Overview

Celestial integrates with Hypervisors, provisioning and central logging systems, all the configuration data is kept under **/etc/celestial/celesitlial.edn** using The link:https://github.com/edn-format/edn[EDN] file format (Clojure's native data representation).

The configuration file is divided to the following sections:

*   Celestial properties like: ports, log settings and cert credentials.
*   Hypervisors where AWS, Openstack , Proxmox properties are set in matching sections.
*   Redis settings
*   SSH settings, mainly the private key path used to connect to remote instances.
*   Hooks, where we can set actions to be invoked post machine creation etc..

**See the <<Openstack>>, <<Digitalocean>>, <<KVM>>, <<GCE>> and <<AWS>> sections for specific hypervisor configuration options.**

### Celestial

The Celestial section (situated on top) contains the configuration options of the Celestial server itself:
```clojure
{
 :celestial {
   :port 8082 
   :https-port 8443
   :log {
     :level :info
     :path "celestial.log"
     :gelf {
	 :host "192.168.1.1"
	 :type :kibana4
	}
   }

   :cert {
     :keystore "foo.keystore"
     :password "foobar"
   }

   :job {
     :status-expiry 5
      :lock {
        :expiry 30
        :wait-time 5
      }
   }

   ; disabled by default
   :nrepl {
     :port 7888
   }
 }
} 
```

[options="header"]
.Mandatory Settings
|===
|Section|Property|Description|Comments

.2+| ports
| port
| Standard http port
| Used for non secured anonymous operations only

| https-port
| Secured https port
| Used for secured RESTful API operations

.2+| log
| level
| Default logging level
| Optional values include: trace, debug, info, error.

| path
| Where the log file is store locally
| Recommend value for production is /var/log/celestial.log

.2+| cert
| keystore
| Java keystore file
| If no file found a file is generated with default password.

| password
| Keystore password
| This password will be used to generate a default keystore or to use an existing one.
|===


[options="header"]
.Optional Settings
|===
|Section|Property|Description|Comments

.2+| gelf
| host
| Host url of a link:https://www.graylog.org/resources/gelf/[GELF] enabled log server
|

| type
| Type of central logging either :kibana3/:kibana4 )
| See <<Integration>> on how to incorporate celestial with link:http://www.elasticsearch.org/overview/kibana/[kibana].

| nrepl
| port
| Remote https://github.com/clojure/tools.nrepl[nrepl] connection for debugging, run only within a secure tunnel, emitting this settings will cause it to be disabled.
| Connecting remotely is possible using lein repl :connect host:port

.3+| job
| lock expiry
| The max time (in minutes) that a lock will be held for a job (on a system) beyond this threshold the job is considered as failed (lock is released).
| 5 minutes by default.

| lock wait-time
| The max time (in minutes) that a job will wait in order to obtain a lock on a system before giving up and failing.
| 5 minutes by default.

| status-expiry
| How long the finished jos will be kept.
| 5 minutes by default.

|===

=== Hooks

Celestial supports the notion of running hook functions after operation failure and success, one use case is registering hostnames in a link:http://www.thekelleys.org.uk/dnsmasq/doc.html[dnsmasq] server instance, notifying external systems is another. 

A Hook gets notified with an event stating the workflow that lead to it and its status, for an implementation hook example please see this link:https://github.com/celestial-ops/celestial-core/blob/master/src/hooks/dnsmasq.clj[example].


Hooks can be enabled by declaring them in celestial.edn, the statement includes the hooks ns followed by the called function, arguments declared within it will be passed to the function call as well.

```clojure
{
 ; rest omitted
 :hooks {
   hooks.dnsmasq/update-dns {
    :dnsmasq "192.168.1.1" :user "name" :domain "local"
 }
}
```

== Hypervisors

=== AWS

Celestial supports Amazon AWS EC2 machines (see <<Matrix>>) in this section we will go through configuring Celestial to create AWS based systems.

AWS configuration goes under the hypervisor/aws section in the link:#overview[configuration] file:

```clojure
{
  :hypervisor {
   :dev {
     :aws {
       :access-key ""
       :secret-key ""
       :ostemplates {
         :ubuntu-12.04 {:ami "" :flavor :debian}
         :centos-6 {:ami "" :flavor :redhat}
       }
      }
    }
  }
}
```

[options="header"]
.AWS configuration
|===
| Property | Description
| access-key | AWS access key
| secret-key | AWS API secret key
| ostemplates | Mappings between system os key to AMI and flavor (redhat or debian).
|===


An AWS based system has the following form (see <<Model>>):

```clojure
{
  :env :dev
  :owner "username"

  :machine {
    :hostname "red1" :user "ubuntu"
    :domain "local" :os :ubuntu-12.10
  }

  :aws {
    :instance-type "t1.micro" 
    :key-name "celestial" 
    :endpoint "ec2.eu-west-1.amazonaws.com"
  }

  :type "redis"
} 
```

.AWS System
|===
|Section|Property|Description|Comments
.3+| aws | instance-type | EC2 instance type | See link:https://aws.amazon.com/ec2/instance-types/[docs].

| key-name
| The EC2 machine key pair name.
| This key should match the default local machine SSH key pair that is used to SSH into the remote machines (usually ~/.ssh/id_rsa).

| endpoint
| The AWS endpoint that will receive request to setup this machine.
| See link:http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region[endpoint] list.

.4+| machine
| os
| Key value of mapped AWS AMI
| See <<Configuration>> on how to set this up

| user
| The AMI user name
| In Ubuntu based AMI this is usually set as ubuntu

| hostname
| Instance hostname
| The hostname and domain will be set on the remote machine

| domain
| Instance domain

|===


=== GCE

link:https://cloud.google.com/compute/[Google Compute] is supported with the following configuration and model

In order to set up GCE under the link:#overview[configuration] section:


```clojure
:hypervisor {
  :dev {
    :gce {
      :ostemplates {
        :ubuntu-15.10  {
           :image  "projects/ronen-playground/global/images/ubuntu-1510-puppet-382-1451476982"
           :flavor :debian
        }

        :centos-6 {
           :image "projects/ronen-playground/global/images/centos-6-puppet-382-1451221785"
           :flavor :redhat
        }
      }
       :service-file "/home/ronen/compute-playground.json"
    }
  }
}
``` 
.GCE configuration
|===
|Section|Property|Description|Comments

| ostemplates
|
| Mapping from OS key to its GCE image
| 

| service file
|
| A json file containing authentication info see link:https://cloud.google.com/storage/docs/authentication#generating-a-private-key[docs]
| 

|===

A GCE based system has the following form:

```clojure
{
 :env :dev 

 :owner "admin"

 :machine {
  :hostname "red1" :user "ronen" 
  :domain "local" :os :ubuntu-15.10
 }

 :gce {
  :machine-type "n1-standard-1" 
  :zone "europe-west1-d"
  :tags ["ssh-enabled"]
  :project-id "ronen-playground"
 }

 :type "redis"
}
```
=== Digitalocean

link:https://www.digitalocean.com/[Digitalocean] is supported with the following configuration and model

In order to set up Digitalocean under the link:#overview[configuration] section:

```clojure
:hypervisor {
  :dev {
    :digital-ocean {
      :token ""
      :ssh-key ""
      :ostemplates {
         :ubuntu-14.04  {:image "ubuntu-14-04-x64" :flavor :debian}
      }
     }
   }
}
``` 
.Digitalocean configuration

|===
|Section|Property|Description|Comments

| token
|
| Digitalocean authentication token
| 

| ssh-key 
|
| The ssh key id defined in Digitialocean for passwordless access to droplets.
| 

| ostemplates
|
| Mapping from OS key to its Digitalocean image
| Please see link:#packer[packer] on how to create a template

|===

A Digitalocean based system has the following form:

```clojure
{
 :env :dev 

 :owner "admin"

 :machine {
   :hostname "red1" :user "root" 
   :domain "local" :os :ubuntu-14.04
 } 

 :digital-ocean {
   :region "lon1" :size "512mb"
   :private_networking false
 }

 :type "redis"
}
```

=== KVM

link:http://www.linux-kvm.org/page/Main_Page[KVM] is supported with the following configuration and model

In order to set up KVM under the link:#overview[configuration] section:


```clojure
:hypervisor {
  :dev {
    :kvm  {
      :nodes {
         :remote {:username "ronen" :host "somehost" :port 22}
       }
      :ostemplates {
         :ubuntu-15.04 {:template "ubuntu-15.04" :flavor :debian}
      }
    }
  }
}
``` 
.KVM configuration
|===
|Section|Property|Description|Comments

| nodes
|
| Mapping from id to ssh connection details
| Please see link:#kvm-libvirt[libvirt] on how to setup authentication

| ostemplates
|
| Mapping from OS key to its KVM template 
| Please see link:#packer[packer] on how to create a template

|===

A KVM based system has the following form:

```clojure
{
 :env :dev 

 :owner "admin"

 :machine {
   :hostname "red1" :user "celestial" :domain "local"
   :os :ubuntu-15.04 :cpu 2 :ram 1024
 } 

 :kvm {
   :node :remote
 }

 :type "redis"
}
```

==== KVM Libvirt

Celetial uses link:https://libvirt.org/[libvirt] in order to access KVM hypervisor instances.

Libvirt uses the underlying ssh key setup in order to access remote hypervisors, this requires us to ssh-copy-id from the Celestial host into KVM hosts we would like to manage:

```bash
$ ssh-copy-id celestial@remote-kvm

```

Another issue is that we can't deploy Celestial itself as a VM within an hypervisor that we would like to manage due to link:https://wiki.libvirt.org/page/TroubleshootMacvtapHostFail[networking limitations] imposed by KVM (install Celestial outside any of the managed hosts).


=== Openstack

Celestial supports Openstack, in this section we will cover how to configure and create systems 

In order to set up Openstack under the link:#overview[configuration]

```clojure
:hypervisor {
  :dev {
    :openstack {
      :endpoint "http://1.2.3.4:5000/v2.0"
      :username ""
      :password ""
      :ostemplates {
        :ubuntu-14.10  {:image "Ubuntu 14.10" :flavor :debian}
      }
      :flavors {
        "m1.small" "2"
      }
      :networks {
       "net-2" "b755f2-xyz-tutut-1234-101150f9a-kljfda"
      }
    }
  }
}
``` 
.Openstack configuration
|===
|Section|Property|Description|Comments
|
| endpoint
| Openstack API endpoint
| 

|
| username
| Openstack username 
| User should have matching permissions 

|
| password
| Openstack user password
| 

| ostemplates
|
| Mapping from OS key to its Openstack image
| 

| flavors
| 
| Mapping from Openstack flavor name to its id
|

| networks
| 
| Mapping from Openstack network name to its id
|

|===

An Openstack based system has the following form:

```clojure
{
 :env :dev

 :owner "admin"

 :machine {
  :hostname "red1" :user "ubuntu"
  :domain "local" :os :ubuntu-14.10
 }

 :openstack {
  :flavor "m1.small"
  :tenant "foo"
  :key-name "bar"
  :security-groups ["default"]
  :networks ["net-1"]
 }

 :type "redis"
}
```

=== Packer
Packer is a tool for creating base images/templates on a large list of hypervisors, link:https://github.com/celestial-ops/celestial-packer[celestial-packer] offers a list of pre-defined templates that are configured to work with Celestial.

=== Matrix


This section comes to list the currently supported and verified systems that Celestial works with, for further support please contact via the <<Support>> channels

.Supported hypervisors
|===
|Name|Versions|Operating systems|Comments
| Proxmox
| {proxmoxversion}
| 12.x < = Ubuntu < = 15.x and Centos
| Only Openvz containers, KVM support is planned 

| AWS
|
| 12.x < = Ubuntu < = 15.x and Centos
|

| Openstack
|
| 12.x < = Ubuntu < = 15.x and Centos
|

| GCE
|
| 12.x < = Ubuntu < = 15.x and Centos
|

| KVM
|
| Ubuntu > = 15.10 
|
|===


Celestial can log to any link:https://github.com/Graylog2/graylog2-docs/wiki/GELF[GELF] enabled logging system (such as kibana, graylog), currently only kibana3/4 linking is supported from the UI.

== Development

Celestial API exposes a JSON based Restful interface (link:http://swagger.io/[swagger] docs):

++++
<iframe src="swagger/index.html" seamless frameborder="0" width="1000px" height="800px"></iframe>
++++


An executable version is available on any Celestial server under https://[hostname]:8443/swagger/index.html. 

A JVM based client library that can be used from any JVM based language is available at link:https://github.com/celestial-ops/groovy-celestial[groovy-celestial]

== Support

Celstial is developed using link:https://github.com/celestial-ops/celestial-core/blob/master/LICENSE-2.0.txt[Apache V2] license, the source code is hosted under link:https://github.com/celestial-ops/celestial-core[github], 

you can reach its main developer at link:https://twitter.com/narkisr[@narkisr].
